language: python

cache:
  directories:
    - "~/.platformio"

# https://docs.platformio.org/en/latest/core/installation.html
# https://docs.platformio.org/en/latest/core/userguide/cmd_update.html
install:
  - pip install -U platformio
  - platformio update

# https://docs.platformio.org/en/latest/boards/index.html
env:
  - BOARD=uno
  - BOARD=leonardo
  - BOARD=ATmega32
  - BOARD=megaatmega2560
  - BOARD=nodemcuv2
  - BOARD=esp-wrover-kit

# https://docs.platformio.org/en/latest/core/userguide/cmd_ci.html
script:
  - set -eo pipefail;
    for example in examples/*; do
      platformio ci --board=$BOARD --lib=. $example/*.ino;
    done