language: python

cache:
  directories:
    - "~/.platformio"

# https://docs.platformio.org/en/latest/core/installation.html
# https://docs.platformio.org/en/latest/core/userguide/cmd_update.html
install:
  - pip install -U platformio
  - platformio update

# https://docs.platformio.org/en/latest/core/userguide/cmd_ci.html
script:
  - set -eo pipefail;
    for example in examples/*; do
      platformio ci --project-conf --lib=. $example/*.ino;
    done
